### ISSUE TITLE
In the Demo on Heroku, the SignUp function doesn't seem to work

### ISSUE THREAD

**Issue by whanyis** [SunPj/silhouette-vuejs-app#4]
In the Demo on Heroku, the SignUp function doesn't seem to work

**Comment by SunPj** [comment]
Hi @whanyis I have just tested it using au@.. email it worked well. Could you give me more info about the issue you faced? Did you use email/password signup or any social button?

**Comment by whanyis** [comment]
> 嗨，@ whanyis，我刚刚使用au @ ..对其进行了测试。您能给我更多有关您遇到的问题的信息吗？您是否使用电子邮件/密码注册或任何社交按钮？
我可以正常进行Sign in，但是当点击Sign up，就一直加载，一直转圈圈

**Comment by whanyis** [comment]
> 嗨，@ whanyis，我刚刚使用au @ ..对其进行了测试。您能给我更多有关您遇到的问题的信息吗？您是否使用电子邮件/密码注册或任何社交按钮？
I can Sign in normally, but when I click Sign up, it keeps loading, keeps circling

**Comment by whanyis** [comment]
I can Sign in normally, but when I click Sign up, it keeps loading, keeps circling。
Look at my video













At 2020-01-16 16:06:52, "Aidar" <notifications@github.com> wrote:

Hi @whanyis I have just tested it using au@.. email it worked well. Could you give me more info about the issue you faced? Did you use email/password signup or any social button?

**Comment by SunPj** [comment]
@whanyis Unfortunately I can't see your video. Have you posted any link here? What browser do you use? Do you have any errors in your developer console? Could you please provide me with the screenshot? Thanks

**Comment by whanyis** [comment]
I use Chrome, I am in China, the use of shadowsocks over the wall, my shadowsocks server in Canada, I put the project after downloaded to a local operation is also unable to Sign up, I use email reply, you may be able to see video in your email, I offer my baidu cloud links and extract the code
baidu cloud links: https://pan.baidu.com/s/1JMVU32X9Jwfw3HazxSOknw      code: 4inn

在 2020-01-17 16:05:30，"Aidar" <notifications@github.com> 写道：

@whanyis Unfortunately I can't see your video. Have you posted any link here? What browser do you use? Do you have any errors in your developer console? Could you please provide me with the screenshot? Thanks

**Comment by SunPj** [comment]
@whanyis Sorry, I can't still see your video. Where are you having such troubles? Is it http://vuejs-slihouette.herokuapp.com/ demo app or your own deployment/localhost? The issue might be due to lack of CAPTHA variable in your environment. I will update docs today. I probably forget to mention that in readme file.

**Comment by whanyis** [comment]
Thank you very much. I can't sign up for both http://vuejs-slihouette.herokuapp.com/ demo appand my local environment。I will see if the problem can be solved locally after you update。May not be able to open the baidu network disk link, sorry

video：https://drive.google.com/open?id=1W9cqlcn_9ULbaiHeAjXAixfv1pq_hA_p
image：https://drive.google.com/open?id=1YgL9nASE1fKF2f9Te5tI5SkyTUNwyYKL

**Comment by SunPj** [comment]
@whanyis Could you please check whether recaptcha is blocked in China? I don't see recaptcha loaded in your video/image. Loading indicator gets away once recaptcha is loaded but you have some issue with loading it.

**Comment by whanyis** [comment]
@SunPj  Yes, I try over the wall, can arrived，Thank you help for the trouble

**Comment by SunPj** [comment]
Hi @whanyis Did you have a chance to test it using some VPN? Does it work well?

**Comment by whanyis** [comment]
@SunPj I use VPN and it works very well. Thank you for your guidance
