### ISSUE TITLE
exporting Recaptcha SiteKey instead of SecretKey in Readme

### ISSUE THREAD

**Issue by ghost** [SunPj/silhouette-vuejs-app#9]
It seems like instead of instructing users to export Recaptcha Secret Key to the environment, you have instructed them to export the Site Key instead

**Comment by SunPj** [comment]
Hi @chaallengerr Secret key is kept in conf file while we need to have Site Key on compiling frontend code as it is taken from ENV variable.

**Comment by ghost** [comment]
Thanks for the clarification. From a security perspective, wouldn't it be better to as well export the secret key to the ENV rather than providing it directly in the conf file?

**Comment by SunPj** [comment]
@chaallengerr If you look at application.conf you will see that most of params are taken from ENV, so it's preferable way to have them there.

**Comment by SunPj** [comment]
@chaallengerr I have just included ENV params info in docs. (Make sure you have all ENV params specified in application.conf such as JDBC_DATABASE_URL, DATABASE_USER, DATABASE_PWD, SENDGRID_API_KEY, RECAPTCHA_SECRETKEY, etc before running the app.)

**Comment by ghost** [comment]
Thanks for farther clarification and the update.
